import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bgGradient'>
    <div className={styles.container}>
      <Head>
        <title>Solimpiada 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beer.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Solimpiada 2022
        </h1>
        <p className={styles.description}>
         Przygotuj się na olimpiade o jakiej nawet nie śniłeś
        </p>
        <p className="subHeader">
          Solenizanci
        </p>

        <div className={styles.grid}>
          <a href="/solga" className={styles.card}>
            <h2>Patryk Solga &rarr;</h2>
            <p>Przyszły psycholog, wspaniały człowiek - lubi piwo</p>
          </a>

          <a href="/wojtek" className={styles.card}>
            <h2>Wojciech Maciejewski</h2>
            <p>Brat Pawła i Hanny, lubi żartować, jego fotel ma dziwny zapach </p>
          </a>
        </div>
      </main>
       <button class="btn fifth" ><a href='https://forms.gle/fEqijVFWQLqLoj11A'>Kliknij mnie aby przejść do ankiety!</a></button>
      <footer className={styles.footer}>
        <p>
        
          Solimpiada 2022
        </p>
      </footer>
    </div>
          </div>
  )
}
